const { DataTypes } = require('sequelize');
const sequelize = require('../config/db');

const Student = sequelize.define('Student', {
  student_id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  mobile: { type: DataTypes.STRING(15), allowNull: false, unique: true },
  email: { type: DataTypes.STRING(150) },
  password: { type: DataTypes.STRING(255), allowNull: false },
  name: { type: DataTypes.STRING(150) },
  dob: { type: DataTypes.DATEONLY },
  gender: { type: DataTypes.ENUM('MALE','FEMALE','OTHER') },
  aadhaar: { type: DataTypes.STRING(12) },
  religion: { type: DataTypes.STRING(50) },
  community_id: { type: DataTypes.INTEGER },
  caste_id: { type: DataTypes.INTEGER },
  comm_address: { type: DataTypes.TEXT },
  comm_city: { type: DataTypes.STRING(100) },
  comm_district_id: { type: DataTypes.INTEGER },
  comm_pincode: { type: DataTypes.STRING(10) },
  perm_address: { type: DataTypes.TEXT },
  perm_city: { type: DataTypes.STRING(100) },
  perm_district_id: { type: DataTypes.INTEGER },
  perm_pincode: { type: DataTypes.STRING(10) },
  alt_mobile: { type: DataTypes.STRING(15) },
  father_name: { type: DataTypes.STRING(150) },
  mother_name: { type: DataTypes.STRING(150) },
  parent_occupation: { type: DataTypes.STRING(100) },
  annual_income: { type: DataTypes.DECIMAL(10,2) },
  board: { type: DataTypes.STRING(100) },
  register_no: { type: DataTypes.STRING(50) },
  last_school: { type: DataTypes.STRING(255) },
  admission_type: { type: DataTypes.ENUM('FIRST_YEAR','LATERAL','PART_TIME'), defaultValue: 'FIRST_YEAR' },
  hostel_required: { type: DataTypes.TINYINT, defaultValue: 0 },
  is_differently_abled: { type: DataTypes.TINYINT, defaultValue: 0 },
  is_ex_servicemen: { type: DataTypes.TINYINT, defaultValue: 0 },
  is_sports_person: { type: DataTypes.TINYINT, defaultValue: 0 },
  is_govt_school: { type: DataTypes.TINYINT, defaultValue: 0 },
  otp: { type: DataTypes.STRING(6) },
  otp_expires: { type: DataTypes.DATE },
  is_verified: { type: DataTypes.TINYINT, defaultValue: 0 },
  refresh_token: { type: DataTypes.TEXT },
}, { tableName: 'students', timestamps: true, underscored: true });

module.exports = Student;
